const insights=[
{id:'global-sentiment',tag:'MARKETS / EXPLAINER',title:'Why global market sentiments matter for Indian sectors',text:'Global risk appetite, commodities, rates and overseas flows can affect Indian sectors in different ways.'},
{id:'business-growth',tag:'BUSINESS / ANALYSIS',title:'Understanding the signal behind business growth',text:'Revenue growth is more meaningful when demand, margins, capacity and cash generation move together.'},
{id:'consumer-demand',tag:'CONSUMER / TRENDS',title:'What changing consumer demand means for Indian business',text:'Changing demand can influence pricing, products, distribution and long-term company strategy.'},
{id:'industrial-shift',tag:'BUSINESS / INDUSTRY',title:'Industrial shifts reshaping competitive strategy',text:'Technology, supply-chain redesign and production economics can change sector leadership.'},
{id:'company-strategy',tag:'BUSINESS / STRATEGY',title:'How company strategy becomes a market signal',text:'Expansion plans, capital allocation and product decisions reveal management priorities early.'},
{id:'risk-signal',tag:'INSIGHT / ANALYSIS',title:'Reading the signals behind market risk',text:'Use rates, volatility, currency moves and sector breadth to separate noise from meaningful change.'}];
const sections=[['Business','Business intelligence, industry shifts, company strategy and consumer trends.','pages/business.html'],['Insights','Analysis and explainers for understanding market and business signals.','pages/insights.html'],['Indian Markets','NIFTY 50, SENSEX and Indian market signals.','pages/indian-markets.html'],['Global Markets','Major global indices and cross-market signals.','pages/global-markets.html'],['Currencies','Key currency pairs and exchange-rate signals.','pages/currencies.html']];
const fmt=v=>typeof v==='number'?v.toLocaleString('en-IN',{maximumFractionDigits:2}):'—';
const pct=v=>typeof v==='number'?(v>=0?'+':'')+v.toFixed(2)+'%':'—';
function paint(id,v){let e=document.getElementById(id);if(!e)return;e.textContent=pct(v);e.className=v>=0?'positive':'negative'}
async function load(){let d=null;try{d=await (await fetch('market-data.json?x='+Date.now())).json()}catch(e){}let i=d?.instruments||{};let n=i.nifty50||{},s=i.sensex||{},u=i.usdinr||{};for(const [id,v] of [['nifty',n.price],['sensex',s.price],['usd',u.price]]){let e=document.getElementById(id);if(e)e.textContent=fmt(v)}paint('niftyC',n.changePct);paint('sensexC',s.changePct);paint('usdC',u.changePct);let up=document.getElementById('updated');if(up&&d?.updatedAt)up.textContent=new Date(d.updatedAt).toLocaleString('en-IN',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'});let g=document.getElementById('global');if(g)g.innerHTML=(d?.global||[]).map(x=>`<div class="tr"><span>${x.name}</span><span>${fmt(x.value)}</span><span class="${x.changePct>=0?'positive':'negative'}">${pct(x.changePct)}</span></div>`).join('')||'<div class="tr"><span>No feed</span><span>—</span><span>—</span></div>';let p=document.getElementById('preview');if(p)p.innerHTML=insights.slice(0,3).map(x=>`<a class="card analysis" href="pages/insights.html#${x.id}"><span class="tag">${x.tag}</span><h3>${x.title}</h3><p>${x.text}</p><span class="meta">Business • Markets • Intelligence</span></a>`).join('')}
function searchSetup(){let m=document.getElementById('modal'),i=document.getElementById('search'),r=document.getElementById('results');if(!m)return;document.getElementById('searchOpen').onclick=()=>{m.classList.add('show');i.focus()};document.getElementById('searchClose').onclick=()=>m.classList.remove('show');m.onclick=e=>{if(e.target===m)m.classList.remove('show')};i.oninput=()=>{let q=i.value.toLowerCase().trim();if(!q){r.innerHTML='<p class="meta">Try company strategy, consumer trends, global markets, NIFTY…</p>';return}let a=[...insights.map(x=>({tag:x.tag,title:x.title,text:x.text,url:'pages/insights.html#'+x.id})),...sections.map(x=>({tag:'SECTION',title:x[0],text:x[1],url:x[2]}))].filter(x=>(x.title+x.text+x.tag).toLowerCase().includes(q));r.innerHTML=a.length?a.map(x=>`<a class="result" href="${x.url}"><small>${x.tag}</small><b>${x.title}</b><div class="meta">${x.text}</div></a>`).join(''):'<p class="meta">No matching result. Try another keyword.</p>'}}
document.addEventListener('DOMContentLoaded',()=>{load();searchSetup()});
